---
title: "run_DynaPrism"
format: html
---

# 0. Set-up

```{r}
#| label: bp-libraries
library(snowfall)
library(gplots)
library(BiocParallel)
library(scran)
library(stats)
library(utils)
library(NMF)
library(Matrix)

library(data.table)
library(digest)
library(tidyverse)
```

```{r}
#| label: bp-functions
source("../BayesPrism/R/classes.R")
source("../BayesPrism/R/new_prism.R")
source("../BayesPrism/R/run_prism.R")
source("../BayesPrism/R/run_gibbs.R")
source("../BayesPrism/R/JointPost_functions.R")
source("../BayesPrism/R/update_reference.R")
source("../BayesPrism/R/optim_functions_MAP.R")
```

```{r}
#| label: dp-functions

source("../R/Omega_tensor.R")
source("../R/DynaPrism.R")
```

Requires dataset-specific variables `myPrism` and `C_t_mtx`. They may be obtained for each dataset running the corresponding quarto notebooks:
- "HuukiMyers_DLPFC": `data_HuukiMyers.qmd`


# 1. Omega

```{r}
#| label: load_regulatory_potential

# Ligand target matrix. Target genes in rows, ligands in columns.
ligand_target_matrix <- readRDS(paste0(data_dir, "nichenetr.dat/ligand_target_matrix_nsga2r_final.rds"))
lr_network <- readRDS(paste0(data_dir, "nichenetr.dat/lr_network_human_21122021.rds"))
```

```{r}
#| label: Omega_setup
oc <- list(
  state = list(ligand_target_matrix = ligand_target_matrix, 
               C_input = C_t_mtx,
               lr_network = lr_network, 
               mask_threshold = 0.1, 
               masking_type = "soft")
  # $type omitted -> defaults to $state
)
```

# 3. DynaPrism

```{r}
  tryCatch({
    dp_res <- save.run.Omega(
      prism          = myPrism,
      omega.control  = oc,
      beta           = 0.7,
      mixture.name   = mix_data_tag,
      reference.name = ref_data_tag,
      opt.control    = list(update.omega = TRUE, optimizer = "MAP"),
      #gibbs.control  = list(chain.length = 1000, burn.in = 500, thinning = 2, seed = 123),
      n.cores        = 10,
      store.C.input  = "hash",     # or "hash" for beta sweeps; omit to default to "value"
      cache.dir      = "../data/runs"
      )
    run_id <- paste0("dp_", mix_data_tag, "_", ref_data_tag, "_", paste0(run.hashes(dp_res), collapse = ""), "_b", gsub("\\.", "p", format(dp_res@control_param$gibbs.control$beta, trim = TRUE, scientific = FALSE)))
  POST(paste0("https://ntfy.sh/", ntfy_topic),
       body = paste0("Saved ", run_id," successfully"),
       add_headers(Title = "✅ R Process Success"))
}, error = function(e) {
  POST(paste0("https://ntfy.sh/", ntfy_topic),
       body = paste0("Getting ", run_id, " failed: ", e$message),
       add_headers(Title = "❌ R Process ERROR", Priority = "high"))
})
```





